### ISSUE TITLE
[1.10.2] Table prefix doesn't work

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectInventories#3] opened 2016-09-02 16:17 UTC
Hallo together,

if I install pji wit a prefix, the installation works fine. But the server doesn't find after a restart the world settings an generate a new entry in the database for each world.

If I install without a prefix, all works fine

**Comment by rockmacaca** [comment] 2016-10-18 22:52
+1

It looks like all that's necessary is to interpolate `prefix("Settings")` into the query string in one spot. Here's the relevant crash log:

```
[18:46:41 ERROR] [STDERR]: java.sql.SQLSyntaxErrorException: Error preparing query: Table 'projectworlds.settings' doesn't exist
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:226)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:376)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:323)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQuery(MariaDbServerPreparedStatement.java:304)
[18:46:41 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[18:46:41 ERROR] [STDERR]:      at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[18:46:41 ERROR] [STDERR]:      at com.gmail.trentech.pji.sql.SQLSettings.getWorld(SQLSettings.java:31)
[18:46:41 ERROR] [STDERR]:      at com.gmail.trentech.pji.EventManager.onLoadWorldEvent(EventManager.java:110)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.LoadWorldEventListener_EventManager_onLoadWorldEvent55.handle(Unknown Source)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:813)
[18:46:41 ERROR] [STDERR]:      at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:755)
[18:46:41 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.func_71247_a(SourceFile:320)
[18:46:41 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:228)
[18:46:41 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:428)
[18:46:41 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)
[18:46:41 ERROR] [STDERR]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Error preparing query: Table 'projectworlds.settings' doesn't exist
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.packet.ComStmtPrepare.read(ComStmtPrepare.java:106)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prepareAndExecute(AbstractQueryProtocol.java:510)
[18:46:41 ERROR] [STDERR]:      at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:365)
[18:46:41 ERROR] [STDERR]:      ... 17 more
```

**Comment by trentech** [comment] 2016-10-18 23:35
Confirmed

**Comment by rockmacaca** [comment] 2016-10-19 00:27
I have a pull ready if you want, but it really is just that one spot that needs fixed in `SQLSettings.java`. I'm already set with a new jar, so if you want to just commit it yourself that's fine.

**Closed** 2016-10-25 19:50 UTC
